micronaut:
  application:
    name: utilitiesApi

datasource:
  default:
    url:
    username:
    password:
    driverClassName:

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
