micronaut:
  application:
    name: utilitiesApi
  server:
    cors:
      enabled: true

jackson:
  dateFormat: "yyyy-dd-MM"

datasources:
  default:
    url: jdbc:mysql://localhost/utilities
    username: me5013zu
    password: ics311
    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none